#!/usr/bin/env ruby

require 'active_support'
require 'active_support/core_ext'
require 'fileutils'
require 'byebug'
require_relative 'erb_file'
require_relative 'config'

include ToYamlViaErb

deploy_dir = "#{__dir__}/../deploy"
build_dir = "#{deploy_dir}/build"

FileUtils.mkdir_p(build_dir)

Dir.glob("#{deploy_dir}/cfn/*.erb").each do |erb_file|
  directory, filename = File.split(erb_file)
  yaml = to_yaml_via_erb(directory, filename, 0, Config.instance)
  File.write("#{build_dir}/#{filename.gsub('.erb','')}", yaml)
end
