#!/usr/bin/env ruby

require 'active_support'
require 'active_support/core_ext'
require 'byebug'
require_relative 'config'
require 'json'
require_relative 'utils'

include Utils

info = {}.merge(Config.instance)

info[:cloudfront_distribution_id] = get_distribution_id

puts JSON.pretty_generate(info)
